Added a Code of conduct file
LangTrans/LangTrans pull request #45
Opened 2023-09-13 21:50 UTC by shubhankarval

Added a _CODE_OF_CONDUCT_ file to the repository. 
Please let me know if you have any questions or if any changes a required.

2023-09-15 13:30 UTC, B-R-P requested changes

2023-09-15 13:30 UTC, B-R-P commented on builtin.yaml
> +multi-line comment: ('''(.*?)'''|"""(.*?)""") # Match multi-line comments
Make name of regex shorter and no spaces

2023-09-15 22:18 UTC, shubhankarval commented
I have made the necessary changes.

2023-09-17 17:23 UTC, B-R-P approved these changes

2023-09-17 17:24 UTC, merged